var tv1= document.getElementById('tv1');
tv1.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=tv1';});
var tv2= document.getElementById('tv2');
tv2.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=tv2';});
var tv3= document.getElementById('tv3');
tv3.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=tv3';});
var tv4= document.getElementById('tv4');
tv4.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=tv4';});
var tv5= document.getElementById('tv5');
tv5.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=tv5';});
var p1= document.getElementById('p1');
p1.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=p1';});
var p2= document.getElementById('p2');
p2.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=p2';});
var p3= document.getElementById('p3');
p3.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=p3';});
var p4= document.getElementById('p4');
p4.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=p4';});
var p5= document.getElementById('p5');
p5.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=p5';});
var h1= document.getElementById('h1');
h1.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=h1';});
var h2= document.getElementById('h2');
h2.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=h2';});
var h3= document.getElementById('h3');
h3.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=h3';});
var h4= document.getElementById('h4');
h4.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=h4';});
var h5= document.getElementById('h5');
h5.addEventListener('click', function(event){window.location.href = 'http://localhost/php/Project1/info.php?id=h5';});
